# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# These environment variables must be set in CircleCI UI
#
# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
# DOCKER_EMAIL   - login info for docker hub
# DOCKER_USER
# DOCKER_PASS

version: 2.1

commands:
  # Only used for local jobs docker execution
  setup_local_docker:
    steps:
      - run:
          name: Use sudo docker in local builds
          command: |
            if [[ $CIRCLE_SHELL_ENV == *"localbuild"* ]]; then
              sudo chmod u+s $(which docker)
            fi

jobs:
  full:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - setup_local_docker
      - checkout
      - run:
          name: Create version.json
          command: |
            jq -n \
            --arg sha "${CIRCLE_SHA1:-}" \
            --arg src_user "${CIRCLE_PROJECT_USERNAME:-mozilla-conduit}" \
            --arg src_repo "${CIRCLE_PROJECT_REPONAME:-phabricator}" \
            --arg build "${CIRCLE_BUILD_URL:-}" \
            '{
            moz_phabricator_commit: (if $sha == "" then null else $sha end),
            moz_phabricator_version: (if $sha == "" then null else $sha end),
            moz_phabricator_source: ("https://github.com/\($src_user)/\($src_repo)"),
            build: (if $build == "" then null else $build end)
            }' > version.json
      - run:
          name: Copy version.json to artifacts
          command: |
            mkdir /tmp/artifacts && \
            cp version.json /tmp/artifacts/version.json
      - run:
          name: Build Docker image
          command: docker build --pull -t $DOCKERHUB_REPO --target production .
      - run:
          name: Build test image
          command: docker compose build test_phab
      - run:
          name: Build test local image
          command: docker compose build test_phab_local
      - run:
          name: Inspect Docker image ID
          command: docker inspect $(docker inspect -f '{{.Id}}' $DOCKERHUB_REPO)
      - run:
          name: Copy imageid to artifacts
          command: docker inspect -f '{{.Id}}' $DOCKERHUB_REPO | tee /tmp/artifacts/docker-image-shasum256.txt
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Deploy to docker hub
          command: |
            [[ -n "$DOCKERHUB_REPO" && -n "$DOCKER_USER" && -n "$DOCKER_PASS" ]] || exit 0
            echo "${DOCKER_PASS}" | docker login -u="${DOCKER_USER}" --password-stdin
            docker tag "$DOCKERHUB_REPO" "$DOCKERHUB_REPO:$CIRCLE_SHA1"
            docker push "$DOCKERHUB_REPO:$CIRCLE_SHA1"
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              docker push "$DOCKERHUB_REPO:latest"
            else
              # Replace forward slashes with hyphens in branch name for Docker tag
              SAFE_BRANCH_NAME=$(echo "$CIRCLE_BRANCH" | tr '/' '-')
              docker tag "$DOCKERHUB_REPO" "$DOCKERHUB_REPO:$SAFE_BRANCH_NAME"
              docker push "$DOCKERHUB_REPO:$SAFE_BRANCH_NAME"
            fi

workflows:
  main:
    jobs:
      - full
