<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'rsrc/css/reviewhelper/reviewhelper-feedback.css' => '0f9cbe2d',
    'rsrc/js/reviewhelper/behavior-reviewhelper-feedback.js' => '08402370',
  ),
  'symbols' => array(
    'javelin-behavior-reviewhelper-feedback' => '08402370',
    'reviewhelper-feedback-css' => '0f9cbe2d',
  ),
  'requires' => array(),
  'packages' => array(),
);
